### ISSUE TITLE
What should I do from labeling step 3?

### ISSUE THREAD

**Issue by recsater** [iosifache/DikeDataset#1]
> To compute the membership on each malware family, a transformer was developed (see the observation above) to "vote" for each available family. For example, if an antivirus engine tag was Trj, then one vote for the trojan family was offered. All tags were consumed in this way and the votes for all families were normalized.

> (see the observation above)

https://github.com/iosifache/dike/blob/main/codebase/scripts/continuous_vt_scan.py

I entered this link, but I didn't know from labeling step 3.

What should I do from labeling step 3?

From

![image](https://user-images.githubusercontent.com/16009827/171989951-0cb67c94-f64a-4273-af1c-56167000a380.png)

To

![image](https://user-images.githubusercontent.com/16009827/171989981-360312c7-626c-4c85-937f-e0dec5f8d02c.png)

**Comment by iosifache** [comment]
Hi, @recsater,
The script only deals with dumping that raw data into a CSV file from Google Cloud Storage. After achieving the [scanning  step](https://github.com/iosifache/DikeDataset#scanning-step), you need to create your own labeling strategy or adapt the dike's one.
You can check dike's implementation in the [`update_malware_labels` function](https://github.com/iosifache/dike/blob/9dae16a92b30af804be2a0ab0664cd3654058446/codebase/modules/dataset/data_folder_scanner.py#L174) from dataset module. There, the votes and tags are processes to obtain the malice and the families' ownership.

**Comment by recsater** [comment]
> Hi, @recsater, The script only deals with dumping that raw data into a CSV file from Google Cloud Storage. After achieving the [scanning step](https://github.com/iosifache/DikeDataset#scanning-step), you need to create your own labeling strategy or adapt the dike's one. You can check dike's implementation in the [`update_malware_labels` function](https://github.com/iosifache/dike/blob/9dae16a92b30af804be2a0ab0664cd3654058446/codebase/modules/dataset/data_folder_scanner.py#L174) from dataset module. There, the votes and tags are processes to obtain the malice and the families' ownership.

First of all, thank you for your reply.

As an additional question, I would like to get exactly the same constant used to make the DikeDataset labels.


Because I'm working on a project to classify malicious code using labels(malware.csv, benign.csv) from DikeDataset.

To do that, can I know the following values?

In Class DataFolderScanner,
self._malware_families
self._malicious_benign_votes_ratio
self._min_ignored_percent

These are defined like
![image](https://user-images.githubusercontent.com/16009827/172065065-a9d1dcd0-2dc9-44dd-8a03-610aa9931817.png)

I am sorry for my bad English. thank you.

**Comment by iosifache** [comment]
dike used a YAML configuration file that contains all the configurable aspects of its functioning. You can find out the values you mentioned by checking the [`dataset` section in the `configuration.yaml` file](https://github.com/iosifache/dike/blob/9dae16a92b30af804be2a0ab0664cd3654058446/data/configuration/configuration.yaml#L3).

And I'm glad to hear that these repositories are useful! Please let me know if you have any other questions, I'm happy to help.
