### ISSUE TITLE
Usage of Dataset

### ISSUE THREAD

**Issue by Aj-it22** [iosifache/DikeDataset#2]
Hi George-Andre Iosif,

I am a student currently pursuing PGDMA in cybersecurity. I am currently working on my research paper about integration of AI enabled malware detection in antivirus software for which i want to use your dataset to train my model due to which I am raising this request. I am so grateful if granted permission to use the dataset. Thanking you in advance

Best Regards,
Aj-it22(Ajit Varma)

**Comment by iosifache** [comment]
Hi @Aj-it22,

Of course, you can use the dataset! This is why I chose to have [a permissive licence](https://github.com/iosifache/DikeDataset?tab=MIT-1-ov-file#readme). Please consider viewing the "Citations" section of the `README.md` file: there are numerous papers and projects that have utilised this dataset (including my B.Sc. implementation, [`dike`](https://github.com/iosifache/dike)).

I will close the issue for now, but feel free to contact me (by opening issues here or through [any other alternative communication channel](https://iosifache.me/about)) if you have any further question.
