### ISSUE TITLE
Malware classification issues

### ISSUE THREAD

**Issue by fjycomes** [iosifache/DikeDataset#3]
I have observed the malware.csv file in the labels directory, and I have seen that you have classified the malware into I have seen that you have classified malware into 9 categories and given the associated probabilities, we can assume that the category with the highest probability is the one that it belongs to, but if we go by this idea, it is obvious that the next six categories are not mentioned because their probabilities are too small, is there something wrong with my understanding of the classification probabilities.
![Uploading pic1.png…]()

**Comment by iosifache** [comment]
Hi @fjycomes,

Could you please re-upload the image? I'll wait for it before responding to your observations.

**Comment by fjycomes** [comment]
> Hi @fjycomes,
> 
> Could you please re-upload the image? I'll wait for it before responding to your observations.

<img width="659" alt="pic1" src="https://github.com/iosifache/DikeDataset/assets/108787470/df1420a3-88f9-42a1-8f4f-d39a03dba025">

May I ask if these data represent the probability of their respective categories, for example, 0.4285714 in the second row and fifth column represents the probability of changing the file to trojan, if so I get the labels of all the files by this probability and found that backdoor, worm, spyware, rootkit, encrypter, downloader, and so on. The files are almost useless, I don't know if my understanding is wrong?

**Comment by iosifache** [comment]
@fjycomes, yes, that is the meaning of the probabilities. Also consider that they are normalised for each entry in the dataset. Why do you think the files are irrelevant?

**Comment by iosifache** [comment]
I will close this issue due to inactivity. Please feel free to reopen it if the information is still relevant for you. Thanks!
